import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const publicSans = Public_Sans({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Easybank',
  description: 'Generated by Nextjs',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-[100vh]'>
      <body className={`${publicSans.className} h-full flex flex-col text-base text-Grayish-Blue lg:text-lg bg-Very-Light-Gray`}>

        <Navbar />
        <main className=''>
        {children}
        </main>
        <Footer />
      </body>
      
    </html>
  )
}
